baseURL = "http://directkidman.github.io/hugoblog/"
languageCode = "ja-jp"
hasCJKLanguage = true
summaryLength = 10
title = "人生自由落下中のブログ"
theme = "Mainroad"
[Author]
    name = "DirectKidman"
    bio = "大学生らしい。理系だけど最近本を読むことにハマっている。"

[Params]
    description = "プログラミングとか音楽とかYoutubeとか私の人生を少し..."
    copyright = "Seiji M"
    opengraph = true
    schema = true
    twitter_cards = true
    readmore = false
    authorbox = true
    toc = true
    pager = true
    post_meta = ["author","date"]
    mainSections = ["posts"]
    dateformat = "2006-01-02"
    mathjax = true
    mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
    mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
    customCSS = ["css/custom.css"]

[Params.style.vars]
    highlightColor = "#00ced1"

[Params.logo]    
    title = "人生自由落下中のブログ"
    subtitle = "思いついたときに書こうかなと。"

[Params.sidebar]
    home = "right"
    list = "right"
    single = false
    widgets = ["search", "recent", "taglist", "social"]

[Params.widgets]
    recent_num = 5
    tags_counter = true

[Params.widgets.social]
    github = "DirectKidman"
    
[taxonomies]
    tag = "tags"


[menu]
    [[menu.main]]
        name = "About me"
        url = "/about"
        weight = 1
    [[menu.main]]
        name = "Project Euler"
        url = "/projecteuler"
        weight = 1
    [[menu.main]]
        name = "投稿一覧"
        url = "/posts"
        weight = 2

        
[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = "0"
        lineAnchors = ""
        lineNoStart = 1
        linenos = true
        lineNumbersInTable = true
        noClasses = true
        style = "manni"
        tabWidth = 4

